### ISSUE TITLE
Favorites do not change after running role

### ISSUE THREAD

**Issue by fcrbe** [gantsign/ansible-role-pin-to-launcher#69]
The configuration does not seem to apply (using gnome). Ubuntu version Ubuntu 18.04.1 LTS. Thought I might need to relogin or reboot after executing the playbook, but neither of them helped.

```yaml
- hosts: localhost

  vars:
    NODEJS_VERSION: "8"
    ansible_distribution_release: "xenial" #trusty

  tasks:
  - name: Link favorites to left bar
    include_role:
      name: gantsign.pin-to-launcher
    vars:
      pin_to_launcher: gnome
      pin_to_launcher_favorites:
        # You'll probably need these apps pinned when using Gnome.
        - application: 'ubiquity.desktop' # The application search/menu
          when_desktop: gnome
        - application: 'org.gnome.Nautilus.desktop' # The file browser
          when_desktop: gnome
        # Pin the applications of your choice below.
        #
        # Tip: run `gsettings get org.gnome.shell favorite-apps` to
        # see the apps you currently have pinned.
        - application: 'firefox.desktop' 
```

`gsettings get org.gnome.shell favorite-apps` keeps on returning my previous favorite apps. Firefox (in the example above) was not added.
